import unittest
from datetime import date

from sqlalchemy import create_engine, text

from planner.category_selector import CategoryAnalytics
from planner.planner_engine import PlannerEngine
from planner.planner_models import PlannerContext, PlannerPreferences, SelectedTopic
from planner.planner_repository import PlannerRepository, build_planning_parameters
from planner.planner_state import WeekStatus


class PlannerRepositoryTests(unittest.TestCase):
    def setUp(self):
        self.engine = create_engine("sqlite:///:memory:")
        self.db = self.engine.connect()
        self._create_schema()

    def tearDown(self):
        self.db.close()
        self.engine.dispose()

    def _create_schema(self):
        self.db.execute(text("""
            create table planner_weeks (
                id text primary key,
                project_id text not null,
                start_date text not null,
                end_date text not null,
                status text not null,
                planning_parameters text not null,
                weekly_briefing text,
                weekly_statistics text not null,
                weekly_review text,
                next_week_options text,
                created_at text default CURRENT_TIMESTAMP,
                updated_at text default CURRENT_TIMESTAMP
            )
        """))
        self.db.execute(text("""
            create unique index planner_weeks_one_active_per_project_idx
            on planner_weeks(project_id)
            where status = 'ACTIVE'
        """))
        self.db.execute(text("""
            create table planner_daily_plans (
                id text primary key,
                week_id text not null,
                session_index integer not null,
                plan_date text not null,
                day_name text not null,
                status text not null,
                objective text,
                briefing text,
                planned_allocations text not null,
                summary text,
                created_at text default CURRENT_TIMESTAMP,
                updated_at text default CURRENT_TIMESTAMP
            )
        """))
        self.db.execute(text("""
            create table planner_activities (
                id text primary key,
                daily_plan_id text not null,
                activity_index integer not null,
                activity_type text not null,
                configuration text not null,
                created_at text default CURRENT_TIMESTAMP,
                updated_at text default CURRENT_TIMESTAMP
            )
        """))
        self.db.commit()

    def _context(self, week_id="week-1"):
        topics = (
            SelectedTopic(id="topic-1", title="Topic 1", order=1),
            SelectedTopic(id="topic-2", title="Topic 2", order=2),
        )
        return PlannerContext(
            categories=("Category A",),
            topics_by_category={"Category A": topics},
            analytics={"Category A": CategoryAnalytics(accuracy=0.8, coverage=0.8)},
            preferences=PlannerPreferences(
                question_pace_seconds=60,
                question_style="exam",
            ),
            number_of_sessions=2,
            planning_budget_minutes=2,
            week_start_date=date(2026, 6, 29),
            week_id=week_id,
        )

    def test_saves_and_reloads_generated_week(self):
        context = self._context()
        week = PlannerEngine().generate_week(context)
        repository = PlannerRepository(self.db)

        saved_week = repository.save_active_week(
            project_id="project-1",
            week=week,
            planning_parameters=build_planning_parameters(context),
        )
        loaded_week = repository.load_active_week(project_id="project-1")

        self.assertIsNotNone(loaded_week)
        self.assertEqual(saved_week.id, "week-1")
        self.assertEqual(loaded_week.id, "week-1")
        self.assertEqual(loaded_week.status, WeekStatus.ACTIVE)
        self.assertEqual(len(loaded_week.daily_plans), 1)
        self.assertEqual(
            [activity.type.value for activity in loaded_week.daily_plans[0].activities],
            ["QUIZ"],
        )
        self.assertEqual(
            loaded_week.daily_plans[0].planned_allocations[0].selected_topics[0].id,
            "topic-1",
        )
        self.assertEqual(
            loaded_week.daily_plans[0].activities[0].configuration.question_style,
            "exam",
        )
        self.assertEqual(
            loaded_week.weekly_briefing,
            "This weekly briefing will be generated by the Professor.",
        )

    def test_duplicate_active_week_is_not_created(self):
        repository = PlannerRepository(self.db)
        first_week = PlannerEngine().generate_week(self._context(week_id="week-1"))
        second_week = PlannerEngine().generate_week(self._context(week_id="week-2"))

        repository.save_active_week(project_id="project-1", week=first_week)
        returned_week = repository.save_active_week(
            project_id="project-1",
            week=second_week,
        )

        self.assertEqual(returned_week.id, "week-1")
        self.assertEqual(
            self.db.execute(text("""
                select count(*)
                from planner_weeks
                where project_id = 'project-1'
                and status = 'ACTIVE'
            """)).scalar(),
            1,
        )


if __name__ == "__main__":
    unittest.main()
