import unittest
from datetime import date

from planner.category_selector import CategoryAnalytics
from planner.planner_engine import PlannerEngine, generate_week
from planner.planner_models import PlannerContext, PlannerPreferences, SelectedTopic
from planner.planner_state import ActivityType, ExecutionStatus, WeekStatus


class PlannerEngineTests(unittest.TestCase):
    def _topics(self, prefix, count):
        return tuple(
            SelectedTopic(id=f"{prefix}-{index}", title=f"{prefix} Topic {index}", order=index)
            for index in range(1, count + 1)
        )

    def test_generate_week_builds_planning_only_week(self):
        context = PlannerContext(
            categories=("Contracts", "Property"),
            topics_by_category={
                "Contracts": self._topics("contract", 2),
                "Property": self._topics("property", 3),
            },
            analytics={
                "Contracts": CategoryAnalytics(accuracy=0.90),
                "Property": CategoryAnalytics(accuracy=0.50),
            },
            preferences=PlannerPreferences(question_pace_seconds=60),
            number_of_sessions=3,
            planning_budget_minutes=2,
            week_start_date=date(2026, 6, 29),
            week_id="week-test",
        )

        week = PlannerEngine().generate_week(context)

        self.assertEqual(week.id, "week-test")
        self.assertEqual(week.status, WeekStatus.PLANNED)
        self.assertEqual(week.start_date, date(2026, 6, 29))
        self.assertEqual(week.end_date, date(2026, 7, 5))
        self.assertEqual(len(week.daily_plans), 3)

        self.assertEqual(week.daily_plans[0].id, "week-test-session-1")
        self.assertEqual(week.daily_plans[0].day_name, "Monday")
        self.assertIn("foundation", week.weekly_briefing)
        self.assertNotEqual(
            week.weekly_briefing,
            "This weekly briefing will be generated by the Professor.",
        )
        self.assertNotEqual(
            week.daily_plans[0].objective,
            "This daily objective will be generated by the Professor.",
        )
        self.assertTrue(week.daily_plans[0].objective)
        self.assertNotEqual(
            week.daily_plans[0].briefing,
            "This daily briefing will be generated by the Professor.",
        )
        self.assertTrue(week.daily_plans[0].briefing)
        self.assertIsNotNone(week.daily_plans[0].summary)
        self.assertEqual(
            [activity.type for activity in week.daily_plans[0].activities],
            [ActivityType.FLASHCARDS],
        )
        self.assertTrue(
            all(
                activity.execution.status == ExecutionStatus.NOT_STARTED
                for activity in week.daily_plans[0].activities
            )
        )

        scheduled_categories = [
            allocation.category
            for daily_plan in week.daily_plans
            for allocation in daily_plan.planned_allocations
        ]

        self.assertEqual(scheduled_categories, [
            "Property",
            "Property",
            "Contracts",
        ])

    def test_daily_plans_preserve_scheduler_allocation_order(self):
        context = PlannerContext(
            categories=("A", "B", "C"),
            topics_by_category={
                "A": self._topics("a", 2),
                "B": self._topics("b", 1),
                "C": self._topics("c", 1),
            },
            analytics={
                "A": CategoryAnalytics(accuracy=0.40),
                "B": CategoryAnalytics(accuracy=0.60),
                "C": CategoryAnalytics(accuracy=0.80),
            },
            preferences=PlannerPreferences(question_pace_seconds=60),
            number_of_sessions=2,
            planning_budget_minutes=2,
            week_start_date=date(2026, 6, 29),
        )

        week = PlannerEngine().generate_week(context)

        self.assertEqual(
            [
                [allocation.category for allocation in daily_plan.planned_allocations]
                for daily_plan in week.daily_plans
            ],
            [["A"], ["B"]],
        )

    def test_empty_context_produces_valid_empty_week(self):
        week = generate_week(
            PlannerContext(
                number_of_sessions=2,
                planning_budget_minutes=30,
                week_start_date=date(2026, 6, 29),
            )
        )

        self.assertEqual(len(week.daily_plans), 0)

    def test_activity_planner_populates_daily_plan_activities(self):
        week = PlannerEngine().generate_week(
            PlannerContext(
                categories=("Genetics",),
                topics_by_category={
                    "Genetics": self._topics("genetics", 3),
                },
                analytics={
                    "Genetics": CategoryAnalytics(accuracy=0.80, coverage=0.80),
                },
                preferences=PlannerPreferences(
                    question_pace_seconds=60,
                    question_style="exam",
                ),
                number_of_sessions=2,
                planning_budget_minutes=2,
                week_start_date=date(2026, 6, 29),
            )
        )

        first_day_activities = week.daily_plans[0].activities

        self.assertEqual(
            [activity.type for activity in first_day_activities],
            [ActivityType.QUIZ],
        )
        self.assertEqual(first_day_activities[0].configuration.num_questions, 2)
        self.assertEqual(first_day_activities[0].configuration.question_style, "exam")
        self.assertEqual(first_day_activities[0].configuration.difficulty, "medium")
        self.assertIsNone(first_day_activities[0].result)


if __name__ == "__main__":
    unittest.main()
