"""Deterministic Professor narrative bridge for Planner weeks.

V1 prepares the narrative structure with placeholders only. It does not call
LLMs, OpenAI, external services, database code, or Professor generation logic.
"""

from dataclasses import replace

from .planner_models import (
    ConversationReference,
    DailyPlan,
    DailySummary,
    HomeworkRecommendation,
    Week,
)


class ProfessorBridge:
    """Attach placeholder Professor narrative structure to planned weeks."""

    WEEKLY_BRIEFING_PLACEHOLDER = "This weekly briefing will be generated by the Professor."
    DAILY_OBJECTIVE_PLACEHOLDER = "This daily objective will be generated by the Professor."
    DAILY_BRIEFING_PLACEHOLDER = "This daily briefing will be generated by the Professor."
    PROFESSOR_DEBRIEF_PLACEHOLDER = "This debrief will be generated after completing the session."
    HOMEWORK_PLACEHOLDER = "This homework recommendation will be generated after the session."
    ACTIVE_RECALL_PLACEHOLDER = "Available after completing today's session."
    OFFICE_HOURS_PLACEHOLDER = "Available after completing today's session."

    def enrich_week(self, week: Week) -> Week:
        """Return a week enriched with deterministic placeholder narratives."""

        return replace(
            week,
            weekly_briefing=self.WEEKLY_BRIEFING_PLACEHOLDER,
            daily_plans=tuple(
                self.enrich_daily_plan(daily_plan)
                for daily_plan in week.daily_plans
            ),
        )

    def enrich_daily_plan(self, daily_plan: DailyPlan) -> DailyPlan:
        """Return a daily plan with placeholder narrative fields."""

        return replace(
            daily_plan,
            objective=self.DAILY_OBJECTIVE_PLACEHOLDER,
            briefing=self.DAILY_BRIEFING_PLACEHOLDER,
            summary=self._build_summary(daily_plan.summary),
        )

    def _build_summary(self, summary: DailySummary = None) -> DailySummary:
        """Create or update a DailySummary with placeholder narrative content."""

        summary = summary or DailySummary()

        return replace(
            summary,
            professor_debrief=self.PROFESSOR_DEBRIEF_PLACEHOLDER,
            homework_recommendations=(
                HomeworkRecommendation(text=self.HOMEWORK_PLACEHOLDER),
            ),
            active_recall_offer=ConversationReference(
                conversation_id="pending-active-recall",
                context=self.ACTIVE_RECALL_PLACEHOLDER,
            ),
            office_hours_offer=ConversationReference(
                conversation_id="pending-office-hours",
                context=self.OFFICE_HOURS_PLACEHOLDER,
            ),
        )
